=== AoV-IndeX/avix-data/data/schema/arcanas.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "ArcanaList",
  "type": "array",
  "items": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Arcana",
    "type": "object",
    "properties": {
      "arcanaId": {
        "type": "string",
        "description": "Stable Arcana identifier"
      },
      "colorId": {
        "type": "string",
        "description": "Arcana color"
      },
      "name": {
        "type": "string",
        "description": "Localized name"
      },
      "asset": {
        "type": "string",
        "description": "Asset path"
      },
      "stats": {
        "$ref": "./stats.schema.json",
        "description": "Stat modifiers"
      }
    },
    "required": [
      "arcanaId",
      "colorId"
    ],
    "additionalProperties": false
  }
}

=== AoV-IndeX/avix-data/data/zh/arcanas.json
[
  {
    "arcanaId": "red_wise",
    "colorId": "red",
    "name": "Wise",
    "asset": "arcanas/red_Wise.webp",
    "stats": {
      "abilityPower": 5.3
    }
  },
  {
    "arcanaId": "red_samurai",
    "colorId": "red",
    "name": "Samurai",
    "asset": "arcanas/red_Samurai.webp",
    "stats": {
      "attackDamage": 3.2
    }
  },
  {
    "arcanaId": "red_berserker",
    "colorId": "red",
    "name": "Berserker",
    "asset": "arcanas/red_Berserker.webp",
    "stats": {
      "attackDamage": 2,
      "physicalPierce": 3.6
    }
  },
  {
    "arcanaId": "red_bloodlust",
    "colorId": "red",
    "name": "Bloodlust",
    "asset": "arcanas/red_Bloodlust.webp",
    "stats": {
      "attackDamage": 2.5,
      "physicalLifesteal": 0.5
    }
  },
  {
    "arcanaId": "red_rampage",
    "colorId": "red",
    "name": "Rampage",
    "asset": "arcanas/red_Rampage.webp",
    "stats": {
      "criticalRate": 0.7,
      "criticalDamage": 3.6
    }
  },
  {
    "arcanaId": "red_guardian",
    "colorId": "red",
    "name": "Guardian",
    "asset": "arcanas/red_Guardian.webp",
    "stats": {
      "attackSpeed": 1,
      "physicalArmor": 2.3,
      "maxHp": 33.7
    }
  },
  {
    "arcanaId": "red_nomad",
    "colorId": "red",
    "name": "Nomad",
    "asset": "arcanas/red_Nomad.webp",
    "stats": {
      "abilityPower": 4.2,
      "magicPierce": 2.4
    }
  },
  {
    "arcanaId": "red_sovereign",
    "colorId": "red",
    "name": "Sovereign",
    "asset": "arcanas/red_Sovereign.webp",
    "stats": {
      "abilityPower": 4.2,
      "attackSpeed": 0.6
    }
  },
  {
    "arcanaId": "red_savage",
    "colorId": "red",
    "name": "Savage",
    "asset": "arcanas/red_Savage.webp",
    "stats": {
      "criticalRate": 1.6
    }
  },
  {
    "arcanaId": "red_blitz",
    "colorId": "red",
    "name": "Blitz",
    "asset": "arcanas/red_Blitz.webp",
    "stats": {
      "attackSpeed": 1.6,
      "criticalRate": 0.5
    }
  },
  {
    "arcanaId": "purple_colossus",
    "colorId": "purple",
    "name": "Colossus",
    "asset": "arcanas/purple_Colossus.webp",
    "stats": {
      "maxHp": 75
    }
  },
  {
    "arcanaId": "purple_cleric",
    "colorId": "purple",
    "name": "Cleric",
    "asset": "arcanas/purple_Cleric.webp",
    "stats": {
      "magicLifesteal": 1.6
    }
  },
  {
    "arcanaId": "purple_tyrant",
    "colorId": "purple",
    "name": "Tyrant",
    "asset": "arcanas/purple_Tyrant.webp",
    "stats": {
      "criticalRate": 0.5,
      "maxHp": 60
    }
  },
  {
    "arcanaId": "purple_reaper",
    "colorId": "purple",
    "name": "Reaper",
    "asset": "arcanas/purple_Reaper.webp",
    "stats": {
      "physicalLifesteal": 1.6
    }
  },
  {
    "arcanaId": "purple_undying",
    "colorId": "purple",
    "name": "Undying",
    "asset": "arcanas/purple_Undying.webp",
    "stats": {
      "maxHp": 60,
      "hpRegen": 4.5
    }
  },
  {
    "arcanaId": "purple_crusader",
    "colorId": "purple",
    "name": "Crusader",
    "asset": "arcanas/purple_Crusader.webp",
    "stats": {
      "physicalLifesteal": 1,
      "magicArmor": 4.1
    }
  },
  {
    "arcanaId": "purple_vampire",
    "colorId": "purple",
    "name": "Vampire",
    "asset": "arcanas/purple_Vampire.webp",
    "stats": {
      "abilityPower": 2.4,
      "magicLifesteal": 1
    }
  },
  {
    "arcanaId": "purple_reliever",
    "colorId": "purple",
    "name": "Reliever",
    "asset": "arcanas/purple_Reliever.webp",
    "stats": {
      "maxHp": 45,
      "hpRegen": 5.2,
      "movementSpeed": 0.4
    }
  },
  {
    "arcanaId": "purple_assassin",
    "colorId": "purple",
    "name": "Assassin",
    "asset": "arcanas/purple_Assassin.webp",
    "stats": {
      "attackDamage": 1.6,
      "movementSpeed": 1
    }
  },
  {
    "arcanaId": "purple_fairy",
    "colorId": "purple",
    "name": "Fairy",
    "asset": "arcanas/purple_Fairy.webp",
    "stats": {
      "attackSpeed": 1,
      "movementSpeed": 1
    }
  },
  {
    "arcanaId": "teal_bastion",
    "colorId": "teal",
    "name": "Bastion",
    "asset": "arcanas/teal_Bastion.webp",
    "stats": {
      "physicalArmor": 9
    }
  },
  {
    "arcanaId": "teal_mythril",
    "colorId": "teal",
    "name": "Mythril",
    "asset": "arcanas/teal_Mythril.webp",
    "stats": {
      "physicalArmor": 5,
      "magicArmor": 5
    }
  },
  {
    "arcanaId": "teal_paladin",
    "colorId": "teal",
    "name": "Paladin",
    "asset": "arcanas/teal_Paladin.webp",
    "stats": {
      "maxHp": 37.5,
      "cooldownReduction": 0.6
    }
  },
  {
    "arcanaId": "teal_monarch",
    "colorId": "teal",
    "name": "Monarch",
    "asset": "arcanas/teal_Monarch.webp",
    "stats": {
      "magicArmor": 9
    }
  },
  {
    "arcanaId": "teal_hexer",
    "colorId": "teal",
    "name": "Hexer",
    "asset": "arcanas/teal_Hexer.webp",
    "stats": {
      "abilityPower": 2.4,
      "cooldownReduction": 0.7
    }
  },
  {
    "arcanaId": "teal_dragoon",
    "colorId": "teal",
    "name": "Dragoon",
    "asset": "arcanas/teal_Dragoon.webp",
    "stats": {
      "attackDamage": 0.9,
      "physicalPierce": 6.4
    }
  },
  {
    "arcanaId": "teal_degenerate",
    "colorId": "teal",
    "name": "Degenerate",
    "asset": "arcanas/teal_Degenerate.webp",
    "stats": {
      "attackSpeed": 0.6,
      "magicPierce": 6.4
    }
  },
  {
    "arcanaId": "teal_templar",
    "colorId": "teal",
    "name": "Templar",
    "asset": "arcanas/teal_Templar.webp",
    "stats": {
      "cooldownReduction": 1
    }
  },
  {
    "arcanaId": "teal_darksider",
    "colorId": "teal",
    "name": "Darksider",
    "asset": "arcanas/teal_Darksider.webp",
    "stats": {
      "magicLifesteal": 0.7,
      "physicalArmor": 5.9
    }
  },
  {
    "arcanaId": "teal_crusader",
    "colorId": "teal",
    "name": "Crusader",
    "asset": "arcanas/teal_Crusader.webp",
    "stats": {
      "physicalArmor": 2.7,
      "magicArmor": 2.7,
      "cooldownReduction": 0.6
    }
  }
]
