=== AoV-IndeX/avix-data/data/schema/talents.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "TalentList",
  "type": "array",
  "items": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Talent",
    "type": "object",
    "properties": {
      "talentId": {
        "type": "string",
        "description": "Stable talent identifier"
      },
      "number": {
        "type": "number",
        "description": "Cardinal number used for ordering"
      },
      "cooldown": {
        "type": "string",
        "description": "Display cooldown text"
      },
      "name": {
        "type": "string",
        "description": "Localized name"
      },
      "description": {
        "type": "string",
        "description": "Localized description"
      },
      "asset": {
        "type": "string",
        "description": "Asset path"
      }
    },
    "required": ["talentId", "number", "cooldown"],
    "additionalProperties": false
  }
}

=== AoV-IndeX/avix-data/data/th/talents.json
[
  {
    "talentId": "heal",
    "number": 1,
    "cooldown": "120s",
    "name": "Heal",
    "description": "Nearby allies instantly restore 15% Max HP and increase 15% Movement Speed for 2s",
    "asset": "talents/Talent01_Heal.webp"
  },
  {
    "talentId": "sprint",
    "number": 2,
    "cooldown": "90s",
    "name": "Sprint",
    "description": "Removes all Slow effects and gain a diminishing (70% - 30%) Movement Speed for 10s",
    "asset": "talents/Talent02_Sprint.webp"
  },
  {
    "talentId": "punish",
    "number": 3,
    "cooldown": "120s",
    "name": "Punish",
    "description": "Punish: Deals (1350 - 2750) True Damage to a nearby Wildling / Minion and stun them for 1s Frostbite: Simultaneously cast on a nearby enemy, dealing (200 - 410) True Damage with 50% Slow for 2s",
    "asset": "talents/Talent03_Punish.webp"
  },
  {
    "talentId": "execute",
    "number": 4,
    "cooldown": "90s",
    "name": "Execute",
    "description": "Instantly attacks nearby enemies, deals True Damage equals Target's 16% Lost HP",
    "asset": "talents/Talent04_Execute.webp"
  },
  {
    "talentId": "flicker",
    "number": 5,
    "cooldown": "120s",
    "name": "Flicker",
    "description": "Teleports a certain distance in the target direction",
    "asset": "talents/Talent05_Flicker.webp"
  },
  {
    "talentId": "roar",
    "number": 6,
    "cooldown": "60s",
    "name": "Roar",
    "description": "Increases 25% Resistance and 10% Damage Dealt, while healing 2% Max HP every second over 6s",
    "asset": "talents/Talent06_Roar.webp"
  },
  {
    "talentId": "daze",
    "number": 7,
    "cooldown": "90s",
    "name": "Daze",
    "description": "Stuns all nearby enemies for 0.75s Then, reduces Targets' 20% Movement Speed, (28 + Lv*2) Armor, and (14 + Lv) Magic Armor for 2.5s",
    "asset": "talents/Talent07_Daze.webp"
  },
  {
    "talentId": "purify",
    "number": 8,
    "cooldown": "100s",
    "name": "Purify",
    "description": "Removes all Debuffs and Control Effects. Gains Super Armor for 1.5s",
    "asset": "talents/Talent08_Purify.webp"
  },
  {
    "talentId": "enfeeble",
    "number": 9,
    "cooldown": "30s",
    "name": "Enfeeble",
    "description": "Reduces nearby enemies' 20% Damage Dealt and gains 20% Damage Reduction for 4s",
    "asset": "talents/Talent09_Enfeeble.webp"
  }
]

=== AoV-IndeX/avix-data/data/en/talents.json
[
  {
    "talentId": "heal",
    "number": 1,
    "cooldown": "120s",
    "name": "Heal",
    "description": "Nearby allies instantly restore 15% Max HP and increase 15% Movement Speed for 2s",
    "asset": "talents/Talent01_Heal.webp"
  },
  {
    "talentId": "sprint",
    "number": 2,
    "cooldown": "90s",
    "name": "Sprint",
    "description": "Removes all Slow effects and gain a diminishing (70% - 30%) Movement Speed for 10s",
    "asset": "talents/Talent02_Sprint.webp"
  },
  {
    "talentId": "punish",
    "number": 3,
    "cooldown": "120s",
    "name": "Punish",
    "description": "Punish: Deals (1350 - 2750) True Damage to a nearby Wildling / Minion and stun them for 1s Frostbite: Simultaneously cast on a nearby enemy, dealing (200 - 410) True Damage with 50% Slow for 2s",
    "asset": "talents/Talent03_Punish.webp"
  },
  {
    "talentId": "execute",
    "number": 4,
    "cooldown": "90s",
    "name": "Execute",
    "description": "Instantly attacks nearby enemies, deals True Damage equals Target's 16% Lost HP",
    "asset": "talents/Talent04_Execute.webp"
  },
  {
    "talentId": "flicker",
    "number": 5,
    "cooldown": "120s",
    "name": "Flicker",
    "description": "Teleports a certain distance in the target direction",
    "asset": "talents/Talent05_Flicker.webp"
  },
  {
    "talentId": "roar",
    "number": 6,
    "cooldown": "60s",
    "name": "Roar",
    "description": "Increases 25% Resistance and 10% Damage Dealt, while healing 2% Max HP every second over 6s",
    "asset": "talents/Talent06_Roar.webp"
  },
  {
    "talentId": "daze",
    "number": 7,
    "cooldown": "90s",
    "name": "Daze",
    "description": "Stuns all nearby enemies for 0.75s Then, reduces Targets' 20% Movement Speed, 30-58 Armor, and 15-29 Magic Armor for 2.5s",
    "asset": "talents/Talent07_Daze.webp"
  },
  {
    "talentId": "purify",
    "number": 8,
    "cooldown": "100s",
    "name": "Purify",
    "description": "Removes all Debuffs and Control Effects. Gains Super Armor for 1.5s",
    "asset": "talents/Talent08_Purify.webp"
  },
  {
    "talentId": "enfeeble",
    "number": 9,
    "cooldown": "30s",
    "name": "Enfeeble",
    "description": "Reduces nearby enemies' 20% Damage Dealt and gains 20% Damage Reduction for 4s",
    "asset": "talents/Talent09_Enfeeble.webp"
  },
  {
    "talentId": "teleport",
    "number": 10,
    "cooldown": "90s",
    "name": "Teleport",
    "description": "Channel for 2s to teleport to an allied structure or minion. The target is immune to damage during the teleport. Cancelling Teleport or using within 30s of activating a Portal reduces its Cooldown by 30s.",
    "asset": "talents/Talent10_Teleport.webp"
  },
  {
    "talentId": "umbral-spawn",
    "number": 11,
    "cooldown": "100s",
    "name": "Umbral Spawn",
    "description": "Reduces the cooldown of all skills 50%. Gains a 300-580 shield and summons a beast that deals 300-580 magic damage and slows enemies",
    "asset": "talents/Talent11_UmbralSpawn.webp"
  }
]

=== AoV-IndeX/avix-data/data/talent-desc.json
[
  {
    "talentId": "heal",
    "number": 1,
    "name": "Heal",
    "cooldown": "120s",
    "description": "Nearby allies instantly restore 15% Max HP and increase 15% Movement Speed for 2s",
    "asset": "talents/Talent01_Heal.webp"
  },
  {
    "talentId": "sprint",
    "number": 2,
    "name": "Sprint",
    "cooldown": "90s",
    "description": "Instantly attacks nearby enemies, deals True Damage equals Target's 16% Lost HP",
    "asset": "talents/Talent02_Sprint.webp"
  },
  {
    "talentId": "punish",
    "number": 3,
    "name": "Punish",
    "cooldown": "120s",
    "description": "Removes all Debuffs and Control Effects. Gains Super Armor for 1.5s",
    "asset": "talents/Talent03_Punish.webp"
  },
  {
    "talentId": "execute",
    "number": 4,
    "name": "Execute",
    "cooldown": "90s",
    "description": "Reduces nearby enemies' 20% Damage Dealt and gains 20% Damage Reduction for 4s",
    "asset": "talents/Talent04_Execute.webp"
  },
  {
    "talentId": "flicker",
    "number": 5,
    "name": "Flicker",
    "cooldown": "120s",
    "description": "Teleports a certain distance in the target direction",
    "asset": "talents/Talent05_Flicker.webp"
  },
  {
    "talentId": "roar",
    "number": 6,
    "name": "Roar",
    "cooldown": "60s",
    "description": "Increases 25% Resistance and 10% Damage Dealt, while healing 2% Max HP every second over 6s",
    "asset": "talents/Talent06_Roar.webp"
  },
  {
    "talentId": "daze",
    "number": 7,
    "name": "Daze",
    "cooldown": "90s",
    "description": "Stuns all nearby enemies for 0.75s Then, reduces Targets' 20% Movement Speed, (28 + Lv*2) Armor, and (14 + Lv) Magic Armor for 2.5s",
    "asset": "talents/Talent07_Daze.webp"
  },
  {
    "talentId": "purify",
    "number": 8,
    "name": "Purify",
    "cooldown": "100s",
    "description": "Removes all Slow effects and gain a diminishing (70% - 30%) Movement Speed for 10s",
    "asset": "talents/Talent08_Purify.webp"
  },
  {
    "talentId": "enfeeble",
    "number": 9,
    "name": "Enfeeble",
    "cooldown": "30s",
    "description": "Punish: Deals (1350 - 2750) True Damage to a nearby Wildling / Minion and stun them for 1s Frostbite: Simultaneously cast on a nearby enemy, dealing (200 - 410) True Damage with 50% Slow for 2s",
    "asset": "talents/Talent09_Enfeeble.webp"
  }
]

=== AoV-IndeX/avix-data/data/vi/talents.json
[
  {
    "talentId": "heal",
    "number": 1,
    "cooldown": "120s",
    "name": "Cấp Cứu",
    "description": "Hồi 15% máu cho bản thân và những đồng minh xung quanh, đồng thời tăng 15% tốc chạy cho cả nhóm trong 2 giây.",
    "asset": "talents/Talent01_Heal.webp"
  },
  {
    "talentId": "sprint",
    "number": 2,
    "cooldown": "90s",
    "name": "Tốc Hành",
    "description": "Tăng 30% tốc chạy trong 10 giây. Kích hoạt lập tức xoá trạng thái bị làm chậm đang gánh chịu đồng thời giảm 50% hiệu ứng bị làm chậm khi đang chạy nhanh. Ngoài ra khi rời giao tranh được tăng 20% tốc chạy.",
    "asset": "talents/Talent02_Sprint.webp"
  },
  {
    "talentId": "punish",
    "number": 3,
    "cooldown": "120s",
    "name": "Trừng Trị",
    "description": "Gây 1350 sát thương chuẩn lên lính và quái rừng xung quanh đồng thời làm choáng chúng trong 1 giây. Lưu trữ mỗi 45 giây, tối đa lưu trữ 2 lần.",
    "asset": "talents/Talent03_Punish.webp"
  },
  {
    "talentId": "execute",
    "number": 4,
    "cooldown": "90s",
    "name": "Bộc Phá",
    "description": "Chuyển 16% máu đã mất của tướng địch thành sát thương chuẩn lên chúng trong phạm vi.",
    "asset": "talents/Talent04_Execute.webp"
  },
  {
    "talentId": "flicker",
    "number": 5,
    "cooldown": "120s",
    "name": "Tốc Biến",
    "description": "Lập tức biến theo hướng chỉ định một khoảng ngắn.",
    "asset": "talents/Talent05_Flicker.webp"
  },
  {
    "talentId": "roar",
    "number": 6,
    "cooldown": "60s",
    "name": "Gầm Thét",
    "description": "Tăng 15% kháng hiệu ứng, 10% sát thương và 15% hút máu, 30% hút máu phép, kéo dài 7 giây.",
    "asset": "talents/Talent06_Roar.webp"
  },
  {
    "talentId": "daze",
    "number": 7,
    "cooldown": "90s",
    "name": "Ngất Ngư",
    "description": "Làm choáng tất cả kẻ địch lân cận trong 0.75 giây và làm chậm chúng 20% đồng thời giảm 30-58 giáp, 15-29 giáp phép trong 2.5 giây.",
    "asset": "talents/Talent07_Daze.webp"
  },
  {
    "talentId": "purify",
    "number": 8,
    "cooldown": "100s",
    "name": "Thanh Tẩy",
    "description": "Hóa giải tất cả hiệu ứng bất lợi và khống chế, đồng thời miễn dịch với khống chế trong 1.5 giây.",
    "asset": "talents/Talent08_Purify.webp"
  },
  {
    "talentId": "enfeeble",
    "number": 9,
    "cooldown": "30s",
    "name": "Suy Nhược",
    "description": "Giảm 20% sát thương của kẻ địch lân cận gây ra đồng thời tăng 20% miễn thương cho bản thân trong 4 giây.",
    "asset": "talents/Talent09_Enfeeble.webp"
  },
  {
    "talentId": "teleport",
    "number": 10,
    "cooldown": "90s",
    "name": "Dịch Chuyển",
    "description": "Sau 2 giây niệm chú sẽ dịch chuyển đến công trình phe ta hoặc bên cạnh lính phe ta. Trong khi dịch chuyển, đơn vị đã chọn miễn nhiễm sát thương. Huỷ dịch chuyển hoặc sử dụng cổng dịch chuyển trong vòng 30 giây sẽ giảm 30 giây hồi chiêu.",
    "asset": "talents/Talent10_Teleport.webp"
  },
  {
    "talentId": "umbral-spawn",
    "number": 11,
    "cooldown": "100s",
    "name": "Ma Chủng Hắc Ám",
    "description": "Giảm 50% hồi chiêu của tất cả chiêu thức. Nhận 300-580 lá chắn và triệu hồi ma vật gây 300-580 sát thương phép kèm làm chậm địch",
    "asset": "talents/Talent11_UmbralSpawn.webp"
  }
]
